app_ventas/urls.py
from django.urls import path
from . import views, views_graficos

urlpatterns = [
    # Urls Ventas
    path('', views.index, name='index'),
    path('listar_bebidas', views.listar_bebidas, name='listar_bebidas'),
    path('agregar/', views.agregar_bebida, name='agregar_bebida'),
    path('editar/<int:id>/', views.editar_bebida, name='editar_bebida'),
    path('eliminar/<int:id>/',
         views.eliminar_bebida, name='eliminar_bebida'),
    path('registrar_venta/', views.registrar_venta, name='registrar_venta'),
    path('ventas/', views.listar_ventas, name='listar_ventas'),
    path('total_ventas/', views.total_ventas, name='total_ventas'),
    path('eliminar_venta/<int:id>/', views.eliminar_venta, name='eliminar_venta'),
    # Carrito
    path('agregar_al_carrito/', views.agregar_al_carrito,
         name='agregar_al_carrito'),
    path('cambiar-cantidad-carrito/', views.cambiar_cantidad_carrito,
         name='cambiar_cantidad_carrito'),
    # Urls Gastos
    path('gastos/', views.listar_gastos, name='listar_gastos'),
    path('gastos/agregar/', views.agregar_gasto, name='agregar_gasto'),
    path('gastos/editar/<int:id>/', views.editar_gasto, name='editar_gasto'),
    path('gastos/eliminar/<int:id>/delete',
         views.eliminar_gasto, name='eliminar_gasto'),
    path("total_gastos/", views.total_gastos, name="total_gastos"),
    # Urls User
    path("crearUser/", views.crearUser, name="crearUser"),
    path("signout/", views.signout, name="signout"),
    path("signin/", views.signin, name="signin"),
    path("crearSuperUser/", views.crearSuperUser, name="crearSuperUser"),
    # Carrito
    path('carrito/agregar/', views.agregar_al_carrito, name='agregar_al_carrito'),
    path('carrito/eliminar/', views.eliminar_del_carrito,
         name='eliminar_del_carrito'),
    path('carrito/completar/', views.completar_compra, name='completar_compra'),
    # Urls Graficos
    path('ventas_mensuales/', views.ventas_mensuales, name='ventas_mensuales'),
    path('gastos_mensuales/', views.gastos_mensuales, name='gastos_mensuales'),
    path('ventas_diarias/', views.ventas_diarias, name='ventas_diarias'),
    path('gastos_diarios/', views.gastos_diarios, name='gastos_diarios'),
    path('ventas_semanales/', views.ventas_semanales, name='ventas_semanales'),
    path('gastos_semanales/', views.gastos_semanales, name='gastos_semanales'),
    path('ventas_anuales/', views.ventas_anuales, name='ventas_anuales'),
    path('gastos_anuales/', views.gastos_anuales, name='gastos_anuales'),
    # Rutas para las vistas que renderizan las plantillas de los gráficos
    path('ver_ventas_mensuales/', views_graficos.ver_ventas_mensuales,
         name='ver_ventas_mensuales'),
    path('ver_gastos_mensuales/', views_graficos.ver_gastos_mensuales,
         name='ver_gastos_mensuales'),
    path('ver_ventas_diarias/', views_graficos.ver_ventas_diarias,
         name='ver_ventas_diarias'),
    path('ver_gastos_diarios/', views_graficos.ver_gastos_diarios,
         name='ver_gastos_diarios'),
    path('ver_ventas_semanales/', views_graficos.ver_ventas_semanales,
         name='ver_ventas_semanales'),
    path('ver_gastos_semanales/', views_graficos.ver_gastos_semanales,
         name='ver_gastos_semanales'),
    path('ver_ventas_anuales/', views_graficos.ver_ventas_anuales,
         name='ver_ventas_anuales'),
    path('ver_gastos_anuales/', views_graficos.ver_gastos_anuales,
         name='ver_gastos_anuales'),
    path("link_graficos/", views.link_graficos, name="link_graficos"),
    # Nuevos graficos:
]

django_ventas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("app_ventas.urls"))
]

app_ventas/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

from django.db import models


class Bebida(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre


class Venta(models.Model):
    fecha = models.DateTimeField(auto_now_add=True)
    total = models.DecimalField(max_digits=10, decimal_places=2)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"Fecha: {self.fecha}  Total: {self.total}"


class DetalleVenta(models.Model):
    venta = models.ForeignKey(
        Venta, related_name='detalles', on_delete=models.CASCADE)
    bebida = models.ForeignKey(Bebida, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.bebida} - cantidad: {self.cantidad} - precio: {self.precio}"


class Gasto(models.Model):
    descripcion = models.CharField(max_length=255)
    monto = models.DecimalField(max_digits=10, decimal_places=2)
    fecha_gasto = models.DateTimeField(auto_now_add=True)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.descripcion} - {self.monto} el {self.fecha_gasto}'


class Carrito(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    creado = models.DateTimeField(auto_now_add=True)
    actualizado = models.DateTimeField(auto_now=True)
    completado = models.BooleanField(default=False)


class ItemCarrito(models.Model):
    carrito = models.ForeignKey(
        Carrito, related_name='items', on_delete=models.CASCADE)
    bebida = models.ForeignKey(Bebida, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField(default=1)
    precio = models.DecimalField(max_digits=10, decimal_places=2)

    def subtotal(self):
        return self.cantidad * self.precio

    def __str__(self):
        return f'{self.cantidad} x {self.bebida.nombre}'

app_ventas/forms.py
from django import forms
from .models import Bebida, Venta, Gasto
from calendar import month_name
from datetime import datetime, time


class BebidaForm(forms.ModelForm):

    class Meta:
        model = Bebida
        fields = ["nombre", "descripcion", "precio", "stock"]
        widgets = {
            'nombre': forms.TextInput(attrs={"class": "form-control", "placeholder": "Escribe un nombre"}),
            'descripcion': forms.Textarea(attrs={"class": "form-control", "placeholder": "Escribe una descripcion"}),
            'precio': forms.NumberInput(attrs={"class": "form-control", "placeholder": "Escribe el precio"}),
            'stock': forms.NumberInput(attrs={"class": "form-control", "placeholder": "Escribe el stock"}),
        }


class GastoForm(forms.ModelForm):
    class Meta:
        model = Gasto
        fields = ['descripcion', 'monto']
        widgets = {
            'descripcion': forms.TextInput(attrs={"class": "form-control", "placeholder": "Escribe una descripcion"}),
            'monto': forms.NumberInput(attrs={"class": "form-control", "placeholder": "Escribe el monto"}),
        }


class VentaForm(forms.ModelForm):
    class Meta:
        model = Venta
        fields = ['usuario', 'total']


class DateForm(forms.Form):
    date = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'}),
        label="Seleccionar fecha"
    )


class MonthYearForm(forms.Form):
    MONTHS = [(i, month_name[i]) for i in range(1, 13)]
    YEARS = [(i, i) for i in range(2000, datetime.now().year + 1)]

    month = forms.ChoiceField(choices=MONTHS, label="Mes")
    year = forms.ChoiceField(choices=YEARS, label="Año")

app_ventas/views.py
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
import matplotlib.dates as mdates
from io import BytesIO
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.contrib.auth import login, logout, authenticate
from .forms import BebidaForm, GastoForm, VentaForm,  DateForm, MonthYearForm
from .models import Bebida, Venta, DetalleVenta, Gasto, Carrito, ItemCarrito
from django.contrib.auth.models import User
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
import pandas as pd
import matplotlib.pyplot as plt
from calendar import month_name
from django.utils.translation import gettext_lazy as _
from django import forms
from datetime import datetime, time
from django.utils import timezone
from django.db.models import Q, Sum
import pytz
import matplotlib
matplotlib.use('Agg')
# Create your views here.

argentina_tz = pytz.timezone('America/Argentina/Buenos_Aires')


def index(request):
    return render(request, "inventario/index.html")


def listar_bebidas(request):
    bebidas = Bebida.objects.filter(user=request.user)

    # Buscador de bebidas
    busqueda = request.GET.get("buscar")
    if busqueda:
        bebidas = Bebida.objects.filter(
            Q(nombre__icontains=busqueda) |
            Q(precio__icontains=busqueda)
        ).distinct()

    # Manejar carrito para usuario autenticado
    if request.user.is_authenticated:
        carrito, _ = Carrito.objects.get_or_create(
            usuario=request.user, completado=False)
        total_precio = sum(item.subtotal() for item in carrito.items.all())
    else:
        carrito = None
        total_precio = 0

    return render(request, 'inventario/listar_bebidas.html', {'bebidas': bebidas, 'carrito': carrito, 'total_precio': total_precio})


# User:


def crearUser(request):
    if request.method == "GET":
        return render(request, "user/crearUser.html")
    else:
        if request.POST["password1"] == request.POST["password2"]:
            try:
                user = User.objects.create_user(
                    username=request.POST["username"], password=request.POST["password1"])
                user.save()
                login(request, user)
                return redirect('listar_bebidas')
            except IntegrityError:
                return render(request, "user/crearUser.html", {"error": "El usuario ya existe"})


def crearSuperUser(request):
    if request.method == "GET":
        return render(request, "user/crearSuperUser.html")
    else:
        username = request.POST.get('username')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        es_superusuario = request.POST.get('superuser')
        if password1 == password2:
            if password1 == password2:
                try:
                    user = User.objects.create_user(
                        username=username, password=password1)
                    if es_superusuario:
                        user.is_superuser = True
                        user.is_staff = True
                    user.save()
                    messages.success(
                        request, "Superusuario creado exitosamente.")
                    return redirect('login')  # Redirigir a la página de login
                except Exception as e:
                    messages.error(request, f"Error: {e}")
        else:
            messages.error(request, "Las contraseñas no coinciden.")
    return render(request, 'user/crearSuperUser.html')


def signout(request):
    logout(request)
    return redirect('index')


def signin(request):
    if request.method == "GET":
        return render(request, "user/signin.html")
    else:
        user = authenticate(
            request, username=request.POST["username"], password=request.POST["password"])
        if user is None:
            return render(request, "user/signin.html", {"error": "El usuario o contraseña no coinciden. O necesita abonar el servicio"})
        else:
            login(request, user)
            return redirect('listar_bebidas')


# CRUD Bebidas:

@login_required
def agregar_bebida(request):
    if request.method == 'POST':
        form = BebidaForm(request.POST)
        if form.is_valid():
            new_material = form.save(commit=False)
            new_material.user = request.user
            new_material.save()
            return redirect('listar_bebidas')
    else:
        form = BebidaForm()
    return render(request, 'inventario/agregar_bebida.html', {'form': form})


@login_required
def editar_bebida(request, id):
    bebida = get_object_or_404(Bebida, id=id, user=request.user)
    if request.method == 'POST':
        form = BebidaForm(request.POST, instance=bebida)
        if form.is_valid():
            form.save()
            return redirect('listar_bebidas')
    else:
        form = BebidaForm(instance=bebida)
    return render(request, 'inventario/editar_bebida.html', {'form': form, 'bebida': bebida})


@login_required
def eliminar_bebida(request, id):
    bebida = get_object_or_404(Bebida, pk=id, user=request.user)
    if request.method == 'POST':
        bebida.delete()
        return redirect('listar_bebidas')

# Venta

# No usado por el momento registar_venta.


@login_required
def registrar_venta(request):
    if request.method == 'POST':
        form = VentaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('listar_bebidas')
    else:
        form = VentaForm()
    return render(request, 'inventario/registrar_venta.html', {'form': form})


@login_required
def listar_ventas(request):
    ventas = Venta.objects.filter(usuario=request.user).order_by('-fecha')
    return render(request, 'inventario/listar_ventas.html', {'ventas': ventas})


@login_required
def eliminar_venta(request, id):
    venta = get_object_or_404(Venta, id=id, usuario=request.user)
    if request.method == 'POST':
        venta.delete()
        # Redirige a la vista de listado de ventas
        return redirect('listar_ventas')
    return render(request, 'inventario/eliminar_venta.html', {'venta': venta})


@login_required
def total_ventas(request):
    formd = DateForm(request.GET or None)
    if formd.is_valid() and formd.cleaned_data['date']:
        selected_date = formd.cleaned_data['date']
    else:
        selected_date = timezone.now().astimezone(argentina_tz).date()

    # Inicio y fin del día seleccionado con zona horaria
    start_of_day = datetime.combine(
        selected_date, time.min).astimezone(argentina_tz)
    end_of_day = datetime.combine(
        selected_date, time.max).astimezone(argentina_tz)

    # Filtrar ventas del día
    ventas_dia = Venta.objects.filter(
        fecha__range=(start_of_day, end_of_day),
        usuario=request.user
    ).aggregate(total=Sum('total'))['total'] or 0

    form = MonthYearForm(request.GET or None)
    if form.is_valid() and form.cleaned_data['month'] and form.cleaned_data['year']:
        selected_month = int(form.cleaned_data['month'])
        selected_year = int(form.cleaned_data['year'])
    else:
        now = timezone.now().astimezone(argentina_tz)
        selected_month = now.month
        selected_year = now.year

    # Filtrar ventas del mes
    ventas_mes = Venta.objects.filter(
        fecha__year=selected_year,
        fecha__month=selected_month,
        usuario=request.user
    ).aggregate(total=Sum('total'))['total'] or 0

    return render(request, 'inventario/total_ventas.html', {
        'ventas_dia': ventas_dia,
        'ventas_mes': ventas_mes,
        'form': form,
        'formd': formd
    })


# CRUD Gasto:

@login_required
def listar_gastos(request):
    gastos = Gasto.objects.filter(
        usuario=request.user).order_by('-fecha_gasto')
    return render(request, 'inventario/listar_gastos.html', {'gastos': gastos})


@login_required
def agregar_gasto(request):
    if request.method == 'POST':
        form = GastoForm(request.POST)
        if form.is_valid():
            gasto = form.save(commit=False)
            gasto.usuario = request.user  # Asocia el usuario actual al gasto
            gasto.save()
            return redirect('listar_gastos')
    else:
        form = GastoForm()
    return render(request, 'inventario/agregar_gasto.html', {'form': form})


@login_required
def editar_gasto(request, id):
    gasto = get_object_or_404(Gasto, id=id, usuario=request.user)
    if request.method == 'POST':
        form = GastoForm(request.POST, instance=gasto)
        if form.is_valid():
            form.save()
            return redirect('listar_gastos')
    else:
        form = GastoForm(instance=gasto)
    return render(request, 'inventario/editar_gasto.html', {'form': form, "gasto": gasto})


@login_required
def eliminar_gasto(request, id):
    gasto = get_object_or_404(Gasto, id=id, usuario=request.user)
    if request.method == 'POST':
        gasto.delete()
        return redirect('listar_gastos')
    return render(request, 'inventario/eliminar_gasto.html', {'gasto': gasto})


@login_required
def total_gastos(request):
    formd = DateForm(request.GET or None)
    if formd.is_valid() and formd.cleaned_data['date']:
        selected_date = formd.cleaned_data['date']
    else:
        selected_date = timezone.now().astimezone(argentina_tz).date()

    # Inicio y fin del día seleccionado con zona horaria
    start_of_day = datetime.combine(
        selected_date, time.min).astimezone(argentina_tz)
    end_of_day = datetime.combine(
        selected_date, time.max).astimezone(argentina_tz)

    # Filtrar gastos del día
    gastos_dia = Gasto.objects.filter(
        fecha_gasto__range=(start_of_day, end_of_day),
        usuario=request.user
    ).aggregate(total=Sum('monto'))['total'] or 0

    form = MonthYearForm(request.GET or None)

app_ventas/templates/inventario/agregar_bebida.html
{% extends "layout/base.html" %} {% block content %}

<main class="container my-4">
  <div class="row">
    <div class="col-md-4 offset-md-4">
      <form
        method="POST"
        class="card card-body my-3"
        action="{% url 'agregar_bebida' %}"
      >
        <h1 class="text-center">Crear Producto</h1>
        {{error}} {% csrf_token %} {{form}}
        <button class="btn btn-dark my-2">Guardar</button>
      </form>
    </div>
  </div>
</main>

{% endblock %}

app_ventas/templates/inventario/agregar_gasto.html
{% extends "layout/base.html" %} {% block content %}

<main class="container my-4">
  <div class="row">
    <div class="col-md-4 offset-md-4">
      <form
        method="POST"
        class="card card-body my-3"
        action="{% url 'agregar_gasto' %}"
      >
        <h1 class="text-center">Agregar Gasto</h1>
        {{error}} {% csrf_token %} {{form}}
        <button class="btn btn-dark my-2">Guardar</button>
      </form>
    </div>
  </div>
</main>

{% endblock %}

app_ventas/templates/inventario/editar_bebida.html
{% extends "layout/base.html" %} {% block content %}

<div class="container my-4">
  <div class="row">
    <div class="col-md-4 offset-md-4">
      <form
        method="post"
        action="{% url 'editar_bebida' bebida.id %}"
        class="card card-body"
      >
        <h1>Modificar Producto</h1>
        {% csrf_token %}

        <div style="margin-bottom: 10px">
          <label for="id_nombre">Nombre:</label>
          <input
            type="text"
            name="nombre"
            id="id_nombre"
            value="{{ form.nombre.value|default:bebida.nombre }}"
            class="form-control"
          />
        </div>

        <div style="margin-bottom: 10px">
          <label for="id_descripcion">Descripcion:</label>
          <input
            type="text"
            name="descripcion"
            id="id_descripcion"
            value="{{ form.descripcion.value|default:bebida.descripcion }}"
            class="form-control"
          />
        </div>

        <div style="margin-bottom: 10px">
          <label for="id_precio">Precio:</label>
          <input
            type="number"
            name="precio"
            id="id_precio"
            value="{{ form.precio.value|default:bebida.precio }}"
            class="form-control"
          />
        </div>

        <div style="margin-bottom: 10px">
          <label for="id_stock">Stock:</label>
          <input
            type="number"
            name="stock"
            id="id_stock"
            value="{{ form.stock.value|default:bebida.stock }}"
            class="form-control"
          />
        </div>

        <button type="submit" class="btn btn-dark">Guardar</button>
      </form>
      <form
        action="{% url 'eliminar_bebida' bebida.id %}"
        method="POST"
        onsubmit="return confirm('¿Estás seguro de que deseas eliminar este producto?');"
      >
        {% csrf_token %}
        <button class="btn btn-danger card card-body my-2">Eliminar</button>
      </form>
    </div>
  </div>
</div>

{% endblock %}

app_ventas/templates/inventario/editar_gasto.html
{% extends "layout/base.html" %} {% block content %}

<div class="container my-4">
  <div class="row">
    <div class="col-md-4 offset-md-4">
      <form
        method="post"
        action="{% url 'editar_gasto' gasto.id %}"
        class="card card-body"
      >
        <h1>Modificar Gasto</h1>
        {% csrf_token %}

        <div style="margin-bottom: 10px">
          <label for="id_descripcion">Descripcion:</label>
          <input
            type="text"
            name="descripcion"
            id="id_descripcion"
            value="{{ form.descripcion.value|default:gasto.descripcion }}"
            class="form-control"
          />
        </div>

        <div style="margin-bottom: 10px">
          <label for="id_descripcion">Monto:</label>
          <input
            type="number"
            name="monto"
            id="id_monto"
            value="{{ form.monto.value|default:gasto.monto }}"
            class="form-control"
          />
        </div>
        <button type="submit" class="btn btn-dark">Guardar</button>
      </form>
      <form
        action="{% url 'eliminar_gasto' gasto.id %}"
        method="POST"
        onsubmit="return confirm('¿Estás seguro de que deseas eliminar este gasto?');"
      >
        {% csrf_token %}
        <button class="btn btn-danger card card-body my-2">Eliminar</button>
      </form>
    </div>
  </div>
</div>

{% endblock %}

app_ventas/templates/inventario/eliminar_venta.html
{% extends "layout/base.html" %} {% block content %}
<main class="container py-5">
  <section class="card card-body">
    <h1>Eliminar Venta</h1>
    <p>¿Estás seguro de que deseas eliminar esta venta?</p>
    <form method="POST">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger">Eliminar</button>
      <a href="{% url 'listar_ventas' %}" class="btn btn-secondary">Cancelar</a>
    </form>
  </section>
</main>
{% endblock %}

app_ventas/templates/inventario/index.html
{% extends "layout/base.html" %} {% block content %}

<main class="container py-3 my-3">
  <section class="card card-body">
    <h1 class="h1 text-center">
      ¡ Bienvenidos a la app web para gestionar su negocio !
    </h1>
    <h6 class="text-center lh-sm py-3">
      En esta web, encontrará diferentes métodos para gestionar su negocio con
      mayor eficiencia. <br />
      <br />
      <blockquote>
        "Ingrese su usuario para acceder a la plataforma."
      </blockquote>
      <br />
      Una vez dentro, dispondrá de diversas opciones que le serán de utilidad:
      <br />
      En la sección de Productos, tiene la opción de Vender, donde podrá
      realizar sus ventas <br />
      agregar productos al carrito y luego almacenar la venta. <br />
      También encontrará dos apartados distintos: Ventas y Gastos <br />
      En estos, podrá visualizar la cantidad de ventas que ha realizado y los
      gastos que ha tenido. </br> </br>
      Cualquier duda no dude en cosultar al personal de servicio tecnico
    </h6>
    {% if user.is_authenticated %}
    <h3 class="text-center">Lista de productos</h3>
    <div class="d-grid gap-2 col-6 mx-auto py-3">
      <a
        class="btn btn-dark"
        role="button"
        aria-disabled="true"
        href="{% url 'listar_bebidas' %}"
        >¡Dale click aqui!</a
      >
    </div>
    {% endif %}
  </section>
</main>

{% endblock %}

app_ventas/templates/inventario/link_graficos.html
{% extends "layout/base.html" %} {% block content %}
<main class="container py-5">
  <section class="card card-body">
    <h2>Graficos</h2>
    <h4>Haga click en los botones para ver los graficos</h4>
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <ul class="list-group">
          <li class="list-group-item my-2 text-center">
            <a class="btn btn-dark btn-lg" href="{% url 'ver_ventas_anuales' %}"
              >Ver ventas del año</a
            >
          </li>
          <li class="list-group-item my-2 text-center">
            <a
              class="btn btn-secondary btn-lg"
              href="{% url 'ver_gastos_anuales' %}"
              >Ver gastos del año</a
            >
          </li>
          <li class="list-group-item my-2 text-center">
            <a
              class="btn btn-dark btn-lg"
              href="{% url 'ver_ventas_mensuales' %}"
              >Ver ventas del mes</a
            >
          </li>
          <li class="list-group-item my-2 text-center">
            <a
              class="btn btn-secondary btn-lg"
              href="{% url 'ver_gastos_mensuales' %}"
              >Ver gastos del mes</a
            >
          </li>
        </ul>
      </div>
    </div>
  </section>
</main>
{% endblock %}

app_ventas/templates/inventario/listar_gastos.html
{% extends "layout/base.html" %} {% block content %}
<main class="container py-5">
  <section class="card card-body">
    <h1>Lista de Gastos</h1>
    <a href="{% url 'agregar_gasto' %}">Agregar Gasto</a>
    <table class="table">
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Monto</th>
          <th>Fecha</th>
          <th>Editar</th>
        </tr>
      </thead>
      <tbody>
        {% for gasto in gastos %}
        <tr>
          <td>{{ gasto.descripcion }}</td>
          <td>{{ gasto.monto }}</td>
          <td>{{ gasto.fecha_gasto }}</td>
          <td>
            <form action="{% url 'editar_gasto' gasto.id %}" method="POST">
              {% csrf_token %}
              <button class="btn btn-dark">Editar</button>
            </form>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </section>
</main>

{% endblock %}

app_ventas/templates/inventario/listar_ventas.html
{% extends "layout/base.html" %} {% block content %}
<main class="container py-5">
  <section class="card card-body">
    <h1>Lista de Ventas</h1>
    <table class="table">
      <thead>
        <tr>
          <th>Fecha</th>
          <th>Total</th>
          <th>Eliminar</th>
        </tr>
      </thead>
      <tbody>
        {% for venta in ventas %}
        <tr>
          <td>{{ venta.fecha }}</td>
          <td>{{ venta.total }}</td>
          <td>
            <form
              action="{% url 'eliminar_venta' venta.id %}"
              method="POST"
              style="display: inline"
              onsubmit="return confirm('¿Estás seguro de que deseas eliminar esta venta?');"
            >
              {% csrf_token %}
              <button type="submit" class="btn btn-danger">Eliminar</button>
            </form>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </section>
</main>
{% endblock %}

app_ventas/templates/inventario/registrar_venta.html
{% extends "layout/base.html" %} {% block content %}
<main class="container py-5">
  <section class="card card-body">
    <h1>Lista de Bebidas</h1>
    <form
      class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search"
      method="GET"
    >
      {% csrf_token %}
      <div class="input-group">
        <input
          type="text"
          class="form-control bg-light border-0 small"
          placeholder="Buscar..."
          name="buscar"
          value=""
        />
        <div class="input-group-append">
          <button class="btn btn-outline-primary" type="submit">Buscar</button>
        </div>
      </div>
    </form>

    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">Nombre</th>
          <th scope="col">Precio</th>
          <th scope="col">Cantidad</th>
        </tr>
      </thead>
      <tbody>
        {% for bebida in bebidas %}
        <tr>
          <td><b>{{bebida.nombre|capfirst}}</b></td>
          <td>{{bebida.precio}}</td>
          <td>
            <form action="{% url 'editar_bebida' bebida.id %}" method="POST">
              {% csrf_token %}
              <button class="btn btn-dark">Editar</button>
            </form>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </section>
</main>
{% endblock content %}